title: Recipe Rating Forecast
description: EECS 398 Project at the University of Michigan
theme: just-the-docs

url: https://121jsy.github.io/recipe-rating-forecast

aux_links:
  Template Repository: https://github.com/121jsy/recipe-rating-forecast?tab=readme-ov-file
